/*
 * debug.h
 *
 * Author: Ming Tsang
 * Copyright (c) 2014 HKUST SmartCar Team
 */

#ifndef LINEAR_CCD_DEBUG_H_
#define LINEAR_CCD_DEBUG_H_

//#define DEBUG_PRINT_ENCODER
//#define DEBUG_PRINT_CCD
#define DEBUG_LCD_PRINT_CCD
//#define DEBUG_PRINT_EDGE
#define DEBUG_LCD_PRINT_EDGE
//#define DEBUG_PRINT_TURNING
#define DEBUG_LCD_PRINT_TURNING
//#define DEBUG_PRINT_SERVO_PID
//#define DEBUG_PRINT_GYRO
//#define DEBUG_PRINT_SLOPE
//#define DEBUG_PRINT_CASE
#define DEBUG_LCD_PRINT_CASE
//#define DEBUG_PRINT_SPEED_PID
//#define LIBUTIL_DEBUG_PID_CONTROLLER
//#define DEBUG_PRINT_INTERVAL
#define DEBUG_LCD_PRINT_INTERVAL
//#define DEBUG_MANUAL_CONTROL
//#define DEBUG_PRINT_ERROR_AND_PID
//#define DEBUG_BEEP_CCD_FILL
//#define DEBUG_BEEP_PRE_TURN
//#define DEBUG_BEEP_REVERSE_MOTOR
//#define DEBUG_BEEP_STRAIGHT_IN
#define DEBUG_BEEP_GUESS_CROSSROAD

#endif /* LINEAR_CCD_DEBUG_H_ */
